import type { Config } from 'tailwindcss';

export default {
    content: ['./index.html', './src/**/*.{ts,tsx}'],
    theme: {
        extend: {
            colors: {
                'bg-page':          'var(--color-bg-page)',
                'bg-card':          'var(--color-bg-card)',
                'bg-input':         'var(--color-bg-input)',
                'bg-elevated':      'var(--color-bg-elevated)',
                'bg-toast':         'var(--color-bg-toast)',
                'bg-secondary':     'var(--color-bg-secondary)',
                'bg-tertiary':      'var(--color-bg-tertiary)',
                'bg-placeholder':   'var(--color-bg-placeholder)',
                'bg-grabber':       'var(--color-bg-grabber)',
                'text-primary':     'var(--color-text-primary)',
                'text-secondary':   'var(--color-text-secondary)',
                'text-tertiary':    'var(--color-text-tertiary)',
                'text-quaternary':  'var(--color-text-quaternary)',
                'text-placeholder': 'var(--color-text-placeholder)',
                'text-section':     'var(--color-text-section)',
                'text-on-accent':   'var(--color-text-on-accent)',
                'accent':           'var(--color-accent)',
                'danger':           'var(--color-danger)',
                'danger-strong':    'var(--color-danger-strong)',
                'danger-soft':      'var(--color-danger-soft)',
                'purple':           'var(--color-purple)',
                'border-default':   'var(--color-border)',
                'divider':          'var(--color-divider)',
                'overlay':          'var(--color-overlay)',
                'glass-bg':         'var(--color-glass-bg)',
            },
            fontFamily: {
                sans:    ['MiSans', 'Inter', 'sans-serif'],
                display: ['MiSans', 'Inter', 'sans-serif'],
            },
            fontSize: {
                'xs':   ['11px', { lineHeight: '16px' }],
                'sm':   ['12px', { lineHeight: '18px' }],
                'base': ['14px', { lineHeight: '20px' }],
                'md':   ['15px', { lineHeight: '22px' }],
                'lg':   ['16px', { lineHeight: '24px' }],
                'xl':   ['18px', { lineHeight: '26px' }],
                '2xl':  ['20px', { lineHeight: '28px' }],
                '3xl':  ['24px', { lineHeight: '32px' }],
                '4xl':  ['28px', { lineHeight: '36px' }],
            },
            zIndex: {
                hide:    'var(--z-hide)',
                lowest:  'var(--z-lowest)',
                low:     'var(--z-low)',
                medium:  'var(--z-medium)',
                high:    'var(--z-high)',
                highest: 'var(--z-highest)',
                max:     'var(--z-max)',
            },
            height: {
                navbar: 'var(--navbar-height)',
            },
        },
    },
} satisfies Config;
