export enum RouteName {
    Splash = 'splash',
    Home = 'home',
    CharacterList = 'character-list',
    Me = 'me',
    Login = 'login',
    About = 'about',
    PlayScriptOpening = 'play-script-opening',
    PlayScript = 'play-script',
    PlayScriptHistory = 'play-script-history',
    PlayCharacterOpening = 'play-character-opening',
    PermissionDenied = 'permission-denied',
    CharacterCreate = 'character-create',
    PDF = 'pdf',
    CharacterInteraction = 'character-interaction',
    CharacterDetails = 'character-details',
    CharacterTimbreList = 'character-timbre-list',
    CharacterSchedule = 'character-schedule',
    CharacterStats = 'character-stats',
    CharacterRelationships = 'character-relationships',
    ScriptPreparePlay = 'script-prepare-play',
    ScriptEdit = 'script-edit',
    ScriptRoleEdit = 'script-role-edit',
    ScriptDraft = 'script-draft',
    UserSettings = 'user-settings',
    CancelAccount = 'cancel-account',
    Web = 'web',
}

export enum PDFPageKind {
    PrivacyPolicy = 1,
    TermsOfService = 2,
    AboutTips = 3,
}
